### ISSUE TITLE
Opening bad/non existing file makes NetLogo hang

### ISSUE THREAD

**Issue by arthurhjorth** [NetLogo/LevelSpace#100]
If you try to open a bad or non-existing file in LevelSpace, NetLogo stops working. You can type stuff into the Command Center (e.g. `1 + 1`) but it never actually runs. You also cannot "Halt" out of it.

This is on Windows, and is the case with both interactive and headless models.

**Comment by qiemem** [comment]
What do you mean a bad file?

I can't reproduce with a non-existent file. I get an error:

> Extension exception: NetLogo couldn't read the file "/Users/bryan/Development/NetLogo/nl.hexy/netlogo-gui/target/classes/system/doesntexist.nlogo". Are you sure it exists and that NetLogo has permission to read it?
error while observer running LS:CREATE-MODELS
  called by Command Center

and everything continues to work after dismissing. Are you still seeing this problem?

**Comment by arthurhjorth** [comment]
Oddly, only with `create-interactive-models` now. Maybe I didn't test it properly last time. 

But yes, it still causes it to hang. Are you not getting that on Mac with interactive models?
