### ISSUE TITLE
Possible: user-xxx primitives in models

### ISSUE THREAD

**Issue by arthurhjorth** [NetLogo/LevelSpace#24]
@SethTisue brought up the fact that user-xxx primitives may create problems in child models. I hadn't even thought of this. Need to test and see if it is a problem, in both GUI and Headless models

**Comment by qiemem** [comment]
[This is built into the `user-*` primitives](https://github.com/NetLogo/NetLogo/blob/2d3a9be3744030dee5c2fd535761a0d5684750e9/netlogo-gui/src/main/prim/gui/_usermessage.scala#L33). So it would require a core modification to fix. Honestly, I don't think it's really worth it. It's easy enough to use a gui child model instead as a work around, and it seems reasonable: if you want gui stuff to work, use a gui child model!
