### ISSUE TITLE
Add pooling

### ISSUE THREAD

**Issue by qiemem** [NetLogo/LevelSpace#38]
Pooling needs to be keyed off model contents hash so that if the model is modified on the hard drive, a new one will be loaded.

The reason for this is that the classes of a model aren't unloaded or something.

Need to call clear all on close.

**Comment by qiemem** [comment]
Note that the permgen advantage is moot with Java 8.

**Comment by arthurhjorth** [comment]
By moot, do you mean that it doesn't help, or that there is no permgen issue in java 8?

**Comment by qiemem** [comment]
There is no permgen in Java 8. However, we should check for memory leaks in the heap as it may have just moved the leaks from permgen to heap.

Also, I think we should toss the speed slider connections and just give GUI models their own speed slider. I've often found myself wanting to, for instance, set the speed slider of child models low and parent models high. This would also toss a complicating source of memory leaks.

**Comment by arthurhjorth** [comment]
I think that sounds great! If we can, speed sliders should definitely be
model-specific. Any chance we could make children inherit their parent's
speed? or would that reintroduce the memory leak source?

On Sun, Oct 11, 2015 at 1:59 PM, Bryan Head <notifications@github.com>
wrote:

> There is no permgen in Java 8. However, we should check for memory leaks
> in the heap as it may have just moved the leaks from permgen to heap.
>
> Also, I think we should toss the speed slider connections and just give
> GUI models their own speed slider. I've often found myself wanting to, for
> instance, set the speed slider of child models low and parent models high.
> This would also toss a complicating source of memory leaks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NetLogo/LevelSpace/issues/38#issuecomment-147235330>.
>



-- 
-- 
Arthur Hjorth
PhD Student, Learning Sciences
Center for Connected Learning <http://ccl.northwestern.edu/>
Northwestern University

e: arthur.hjorth@u.northwestern.edu
s: arthurhjorth
m: +1 (773) 943-0013

**Comment by qiemem** [comment]
> Any chance we could make children inherit their parent's speed?

You mean default to their parent's speed? That's definitely doable. But then after that changing one would not affect the other.

**Comment by arthurhjorth** [comment]
I think that's what I meant. But then I thought about it, and I don't think
it's a good idea anymore.

On Sun, Oct 11, 2015 at 2:06 PM, Bryan Head <notifications@github.com>
wrote:

> Any chance we could make children inherit their parent's speed?
>
> You mean default to their parent's speed? That's definitely doable. But
> then after that changing one would not affect the other.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NetLogo/LevelSpace/issues/38#issuecomment-147235624>.
>



-- 
-- 
Arthur Hjorth
PhD Student, Learning Sciences
Center for Connected Learning <http://ccl.northwestern.edu/>
Northwestern University

e: arthur.hjorth@u.northwestern.edu
s: arthurhjorth
m: +1 (773) 943-0013

**Comment by qiemem** [comment]
Ya, I need to think about it more as well. #58 is the issue for it by the way. I'd forgotten I made it.

**Comment by qiemem** [comment]
#59 is the general issue for this. I'm not sure pooling is the right solution, so I'm closing this.
