### ISSUE TITLE
Should have a ls:report-from-descendents too

### ISSUE THREAD

**Issue by arthurhjorth** [NetLogo/LevelSpace#57]
The only way to report from descendents is with `ls:of-descendents`, but it doesn't take arguments. To make it possible to report from descendents with arguments, we should have a `ls:report-from-descendents` too.

**Comment by qiemem** [comment]
`ls:of-descendents` doesn't exist anymore (we're waiting to see if it's needed, since code blocks alleviates much of the pain around inter-generational communication). Besides `ls:let` means arguments aren't really needed anymore.
