### ISSUE TITLE
Newbie Needs Help

### ISSUE THREAD

**Issue by MSUanthro** [NetLogo/LevelSpace#65]
Hi all, I've been away from NetLogo for a while and I am trying to wrap my mind around the coding for LS.  When I downloaded the latest zip file and try to run the LevelSpace Ecology demo I get an error that says ls:_ask-hi isn't defined.  I can run many of the the other models by themselves, and it appears the jars are working, so can anyone help with what I am sure is an obvious error on my part?  Thanks in advance.  Jon

**Comment by arthurhjorth** [comment]
Hi Jon,

First, sorry about that. We're in the final stage of releasing a stable and permanent version of LevelSpace. But our documentation here hasn't been communicating that at all.

This post ended up longer than I hoped, so first a tl;dr:
1. Download [NetLogo 6.x beta] (http://ccl.northwestern.edu/netlogo/6.0beta/)  - final version will release within a month, possibly just a few weeks.
2. Download and build the new ls.jar from [source on the update-netlogo branch](https://github.com/NetLogo/LevelSpace/tree/update-netlogo) or **[email me] (arthur.hjorth@u.northwestern.edu)** and I will send you the latest .jar
3. Read new documentation on [the update-netlogo branch](https://github.com/NetLogo/LevelSpace/tree/update-netlogo)
4. Download [new documentation + demo models](arthur.sesp.northwestern.edu/Constructionism2016/Constructionism2016_LevelSpace_Workshop_Materials.zip) 

Longer version:

The version you are using now is probably the old one, built for NetLogo 5.x. The full version of LevelSpace really should be run using the NetLogo 6.x builds.  You can find the source code for the LevelSpace extension and the _current_ documentation in the [update-netlogo](https://github.com/NetLogo/LevelSpace/tree/update-netlogo) branch.

They are different .jar files, so you will need a new version of both NetLogo, and of the .jar. You can download a beta version of NetLogo 6.x [here] (http://ccl.northwestern.edu/netlogo/6.0beta/) If you know how to, you can build the .jar from the source code on the update-netlogo branch. Alternatively, if you post your email here (or email it to me at arthur.hjorth@u.northwestern.edu) I'll be more than happy to send you the latest .jar, and to keep sending you the updated versions until we bundle the ls.jar with NetLogo (which should be within a month or so - @mrerrormessage will know the timeline better than I do.)

The new version and the shift to 6.x brings some pretty excellent changes to the syntax. You no longer need to use strings for everything, and in general the code for LevelSpace looks like normal NetLogo code. Consequently, the old LevelSpace Ecology demo will _not_ work with the new version. We presented the newest version of LevelSpace at a conference back in February, and Bryan Head ( @qiemem  ) and I wrote a few new models  for that which I have attached up in the zip file in pt. 4.

Given your user name I am just curious: were you planning on using LevelSpace for a course? Is this urgent? Either way, let me/us know, and we'll be very happy to do what we can to help you get started on LevelSpace.

**Comment by mrerrormessage** [comment]
Just wanted to weigh in and say that we haven't yet set a release date for NetLogo 6.x, but the release definitely will not happen before mid-May. Please plan accordingly. Also, to the best of my knowledge, levelspace does not yet work against the latest 6.x beta. There are some breaking changes in 6.x that levelspace isn't yet up-to-date with, although we're working on it.

**Comment by qiemem** [comment]
> Also, to the best of my knowledge, levelspace does not yet work against the latest 6.x beta. There are some breaking changes in 6.x that levelspace isn't yet up-to-date with, although we're working on it.

Just pushed an update which should fix that!

**Comment by MSUanthro** [comment]
Thanks for your quick replies Arthur, Robert and Bryan.  I am looking forward to getting back into the ABM world, and I am especially excited about the multi-level possibilities.  I am an archaeologist who studies cultural transmission and sociopolitical organization, and I used NetLogo in my dissertation research a few years ago.  Now I am looking into continuing where I left off and multi-level modeling is exactly where I wanted to go for the next step in research 

I am not in a particular rush, so for now I guess I can just hang out, brush up on coding, and wait for the cool stuff coming down the pipe.  Thanks again, Jon
