### ISSUE TITLE
Should hiding a model hide its children?

### ISSUE THREAD

**Issue by arthurhjorth** [NetLogo/LevelSpace#70]
Keeping track of windows is going to be  a real issue with models like Jim Levin's. 

I can see more good reasons for doing this than for not doing it. What do you think? Or should we have a special primitive for showing/hiding recursively?

**Comment by arthurhjorth** [comment]
I think no. I really can't see why. But it might be nice with a fast way of doing it recursively down through a model's children?

**Comment by qiemem** [comment]
Let's, you can do this in NetLogo without adding procedures to all your models:

```
let hide-code (word
  "let code ? "
  "foreach ls:models [ "
  "ls:hide ? "
  "if ls:uses-level-space? ? [ "
  "(ls:ask ? [ (run ? ?) ] code) "
  "] "
  "] ")
(run hide-code hide-code)
```

Pretty straightforward.

**Comment by arthurhjorth** [comment]
That's not even close to straightforward, you giant nerd <3  

I think we should consider a `ls:hide-all` that hides all a model's children.

**Comment by qiemem** [comment]
We have decided to create `ls:hide-descendants`.
