### ISSUE TITLE
carefully catching an error and then allowing netlogo to continue causes `ls:let` to throw an NPE

### ISSUE THREAD

**Issue by qiemem** [NetLogo/LevelSpace#73]
wat

**Comment by arthurhjorth** [comment]
hahahahahahaahahahahahaha. This HAS to be caused by something else. Why no earth would this happen? Well, hopefully we'll know soon. Good luck :trollface:

**Comment by qiemem** [comment]
It happened when the carefully was in one procedure called by a button and the ls:let was in another... like the procedures didn't call each other... the button called both. Think it might be the error messes with the context in weird ways.

**Comment by arthurhjorth** [comment]
Interesting. Is there a fix you think?
