### ISSUE TITLE
headlessmodels die if model's netlogo version doesn't match app version

### ISSUE THREAD

**Issue by arthurhjorth** [NetLogo/LevelSpace#78]

**Comment by qiemem** [comment]
This is fine, but the error needs to be clearer.

It will only fail if the NetLogo versions are considered incompatible (and thus require auto-conversion). We can't autoconvert child models as that would be silently changing peoples models in the background (even if we don't save the file, auto-conversion is not perfect and we could end up silently modifying model behavior, which is bad bad bad).

I'm clarifying the error message, including a suggestion for how to fix.

**Comment by qiemem** [comment]
By "this is fine" I mean, it *should* error.
