### ISSUE TITLE
Code Examples

### ISSUE THREAD

**Issue by arthurhjorth** [NetLogo/LevelSpace#80]
I think we should have a few Code Example models in the library. I'm meeting with Uri and Connor sometime this week to talk with them about it. Here are a few things I think would be good as examples:
- A simple, side-by-side model, having a 'thin' parent that just deals with business logic between the two models (WSP + CC comes to mind)
- A model in which agents own models. @qiemem 's Agent Brain model comes to mind. There's even a WinterSim poster to reference for that. But it's a big model, and Code Examples are typically much less elaborate. Having a model in which turtles "plot" the phase diagram of WSP is another option.
- A model pooling example. I'm sure many people will want to use that, and it would be nice of us to provide some boilerplate for that.

Dirk Brockmann's Kicked Oscillator will be included, most likely. Turtles own their own models in that too, but it's a pretty complicated model and not really a "Code Example."

Any other ideas?

**Comment by qiemem** [comment]
There are code examples in there now, so I'm closing. We didn't get agent brains in there. Maybe for 6.1.
